// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaZGLXonkvsyJN2GxWk7t6EQ2LGqNmTxE',
    appId: '1:485819657399:web:550e3babc36a4dbffdf132',
    messagingSenderId: '485819657399',
    projectId: 'advice-ally-demo',
    authDomain: 'advice-ally-demo.firebaseapp.com',
    storageBucket: 'advice-ally-demo.appspot.com',
    measurementId: 'G-KSZ2XFG8CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU8Ma2Vd7ga5_Vukfd2JAdDJ2ccoECeKE',
    appId: '1:485819657399:android:dbd522e71656107cfdf132',
    messagingSenderId: '485819657399',
    projectId: 'advice-ally-demo',
    storageBucket: 'advice-ally-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhkqjqbAoEielZaT6Fa42BAWYm11WJDIk',
    appId: '1:485819657399:ios:da7d425b356dcf7ffdf132',
    messagingSenderId: '485819657399',
    projectId: 'advice-ally-demo',
    storageBucket: 'advice-ally-demo.appspot.com',
    iosBundleId: 'com.example.adviceAllyDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhkqjqbAoEielZaT6Fa42BAWYm11WJDIk',
    appId: '1:485819657399:ios:8f205b3926994b5bfdf132',
    messagingSenderId: '485819657399',
    projectId: 'advice-ally-demo',
    storageBucket: 'advice-ally-demo.appspot.com',
    iosBundleId: 'com.example.adviceAllyDemo.RunnerTests',
  );
}
